:linkattrs:

:sectnums: true
:toc: true

=== Lab Developers
*Lucy Kerner*

*Alexander Jacocks*

*Lukas Vrabec*

*Gabriel Becker*

*Petr Lautrbach*

*Paul Wouters*

*Matej Tyc*

*Sergio Correia*

*Tomas Mraz*

*Marek Haicman*

*Ondrej Moris*

*Radovan Sroka*

*Attila Lakatos*

*Justin Stephenson*

*Matthew Burket*

=== Overview and Prerequisites
In this lab, you learn how to build defense-in-depth in the operating system by implementing the key security technologies available to you in the latest version of Red Hat Enterprise Linux.

In a defense-in-depth approach, you implement security at all layers to build a strong foundation to proactively defend against possible security attacks and breaches. You provide security compliance by using technologies such as OpenSCAP, Audit, Advanced Intrusion Detection Environment (AIDE). You add network security with technologies such as firewalld. You implement access via SELinux process isolation. You implement data security with Linux Unified Key Setup (LUKS), Network Bound Disk Encryption (NBDE), and GNU Privacy Guard (GPG).

Specifically, you use OpenSCAP to scan and remediate against vulnerabilities and configuration security baselines. You also use Network Bound Disk Encryption to securely decrypt your encrypted boot volumes unattended. Throughout your investigation of the security issues in your systems, you use audit logs and the web console, and you automate as much of your tasks as possible using Ansible. You also learn how to use AIDE to look for abnormal behavior. Finally, you discover how to identify yourself and encrypt your communications with GPG and also learn how to use firewalld to dynamically manage firewall rules.

This lab is geared toward systems administrators, cloud administrators and operators, architects, and others working on infrastructure operations management who are interested in learning how to take advantage of the built-in security technologies in Red Hat Enterprise Linux.

The prerequisite for this lab include basic Linux skills gained from Red Hat Certified System Administrator (RHCSA^(R)^) or equivalent system administration skills.

=== Session Goals

In this session, you learn how to:

* Automate security compliance using OpenSCAP to scan and remediate against vulnerabilities and configuration security baselines.
* Use SELinux to isolate running processes to mitigate against attacks.
* Use NBDE to securely decrypt LUKS-encrypted volumes unattended.
* Take advantage of the auditing capabilities and the web console for easier centralized management.
* Use the AIDE to detect intrusions.
* Use GPG to identify yourself and encrypt your communications.
* Use firewalld to dynamically manage firewall rules.

=== Lab Environment
Your entire lab environment is hosted online and includes Red Hat Enterprise Linux and Red Hat Ansible Automation.

You obtain your own unique *GUID*, which you use to access your instance of these Red Hat products for the labs.

Each lab is independent of the others and it is not necessary to perform them sequentially.
