:linkattrs:

:sectnums: true
:toc: true

=== Lab Developers
*Lucy Kerner*, Director, Security Global Strategy and Evangelism, Red Hat^(R)^

*Alexander Jacocks*, Staff Solutions Architect, Red Hat^(R)^

*Lukas Vrabec*, Principal Software Engineer and RHEL Security Product Owner--Red Hat Enterprise Linux^(R)^ (RHEL) Security, Red Hat^(R)^

*Gabriel Becker*, Software Engineer--Security Compliance in Red Hat Enterprise Linux^(R)^ (RHEL) Security, Red Hat^(R)^

*Petr Lautrbach*, Senior Software Engineer—Red Hat Enterprise Linux^(R)^  (RHEL) Security, Red Hat^(R)^

*Paul Wouters*, Senior Software Engineer—Red Hat Enterprise Linux^(R)^  (RHEL) Security, Red Hat^(R)^

*Matej Tyc*, Senior Software Engineer and Tech Lead—Security Compliance in Red Hat Enterprise Linux^(R)^  (RHEL) Security, Red Hat^(R)^

*Sergio Correia*, Senior Software Engineer—Red Hat Enterprise Linux^(R)^  (RHEL) Security, Red Hat^(R)^

*Tomas Mraz*, Principal Software Engineer—Red Hat Enterprise Linux^(R)^  (RHEL) Security, Red Hat^(R)^

*Marek Haicman*, Product Owner—Security Compliance in Red Hat Enterprise Linux^(R)^ (RHEL) Security, Red Hat^(R)^

*Ondrej Moris*, Senior Software Quality Engineer —Red Hat Enterprise Linux^(R)^  (RHEL) Security, Red Hat^(R)^

*Radovan Sroka*, Software Engineer—Red Hat Enterprise Linux^(R)^  (RHEL) Security, Red Hat^(R)^

*Attila Lakatos*, Intern—Red Hat Enterprise Linux^(R)^  (RHEL) Security, Red Hat^(R)^

*Justin Stephenson*, Software Engineer—Identity Management in Red Hat Enterprise Linux^(R)^  (RHEL) Security, Red Hat^(R)^

*Matthew Burket*, Software Engineer—Security Compliance in Red Hat Enterprise Linux^(R)^  (RHEL) Security, Red Hat^(R)^


=== Overview and Prerequisites
In this lab, you learn how to build defense-in-depth in the operating system by implementing the key security technologies available to you in the latest version of Red Hat Enterprise Linux.

In a defense-in-depth approach, you implement security at all layers to build a strong foundation to proactively defend against possible security attacks and breaches. You provide security compliance by using technologies such as OpenSCAP, Audit, Audit Intrusion Detection Environment (AIDE), session recording, and system-wide cryptographic policies. You add network security with technologies such as firewalld. You implement access management with Ansible^(R)^ system roles, and SELinux process isolation. You implement data security with Linux Unified Key Setup (LUKS), Network Bound Disk Encryption (NBDE), and GNU Privacy Guard (GPG).

Specifically, you use OpenSCAP to scan and remediate against vulnerabilities and configuration security baselines. You also use Network Bound Disk Encryption to securely decrypt your encrypted boot volumes unattended. You also take advantage of the system-wide cryptographic policies for further security. Throughout your investigation of the security issues in your systems, you use audit logs and the web console, and you automate as much of your tasks as possible using Ansible. For example, you make automated configuration changes to your systems across multiple versions of Red Hat Enterprise Linux running in your environment using the Systems Roles feature. You also learn how to use AIDE, session recording, logging, and playback to look for abnormal behavior. Finally, you discover how to identify yourself and encrypt your communications with GPG and also learn how to use firewalld to dynamically manage firewall rules.

This lab is geared toward systems administrators, cloud administrators and operators, architects, and others working on infrastructure operations management who are interested in learning how to take advantage of the built-in security technologies in Red Hat Enterprise Linux.

The prerequisite for this lab include basic Linux skills gained from Red Hat Certified System Administrator (RHCSA^(R)^) or equivalent system administration skills.

=== Session Goals

In this session, you learn how to:

* Automate security compliance using OpenSCAP to scan and remediate against vulnerabilities and configuration security baselines.
* Use SELinux to isolate running processes to mitigate against attacks.
* Use NBDE to securely decrypt LUKS-encrypted volumes unattended.
* Take advantage of system-wide cryptographic policies.
* Take advantage of the auditing capabilities and the web console for easier centralized management.
* Use the AIDE to detect intrusions.
* Use GPG to identify yourself and encrypt your communications.
* Use firewalld to dynamically manage firewall rules.
* Configure system-wide cryptographic policies and set a machine in Federal Information Processing Standards (FIPS) mode.
* Take advantage of session recording, logging, and playback features and AIDE to look for abnormal behavior.
* Use systems roles to make multiple automated configuration changes across different versions of Red Hat Enterprise Linux using Red Hat Ansible Automation.


=== Lab Environment
Your entire lab environment is hosted online and includes Red Hat Enterprise Linux and Red Hat Ansible Automation.

You obtain your own unique *GUID*, which you use to access your instance of these Red Hat products for the labs.

Each lab is independent of the others and it is not necessary to perform them sequentially.
