:GUID: %GUID%
:USERNAME: %USERNAME%

:BASTION_PASSWORD: %BASTION_PASSWORD%
:BASTION_IP_ADDRESS: %BASTION_IP_ADDRESS%

:sectnums: true
:toc: true

:toc2:
:linkattrs:

.*Lab Length*
* Medium/Average (~15 minutes)

.*Goal*
The goal of this lab is to understand how you can install the udica tool for generating SELinux security policies for containers and loading the policy for your containers.

=== Introduction
The current solution brings several problems with confining containers. For all containers there is just one general SELinux policy (container_t). This cannot fulfill the ideal balance between security and usability for containers.

For certain use cases container type (container_t) is too strict, such as when some directory is bind mounted to container filesystem namespace. This is required to allow container processes to access this directory. On the other hand, for certain use cases the container type is too loose. There are two main situations when SELinux policy should be tighter. The first one is network controlling, when all container processes can bind to any network port. The second one is capability controlling, when all container processes can use all Linux capabilities.

To bring a solution which can address the disadvantages mentioned above, the Udica tool was created. Udica is a tool for generating SELinux security policies for containers. The whole concept is based on the "block inheritance" feature inside SELinux's Common Intermediate Language (CIL). This is an intermediate language supported by SELinux utilities.

Udica creates a policy which combines templates using rules inherited from a specified CIL block and rules discovered by the inspection of the container JSON (lightweight data-interchange format) file, which contains mount points and ports definitions.

For more information, please visit https://www.redhat.com/en/blog/generate-selinux-policies-containers-with-udica[Red Hat Security Blog].

=== Installing the udica and podman
In this section, you  need to log in to the *rhel8selinux1.{GUID}.internal* system and required packages.

. If not already there, log in to the workstation bastion host as *{USERNAME}*:
+
[%nowrap]
----
ssh -o "ServerAliveInterval 30" %USERNAME%@%BASTION_IP_ADDRESS%
----

    TIP: Use `Ctrl+Shift+V` to paste in the terminal.

. Answer `yes` to accept server's identity if asked, and then input the following password:
+
[%nowrap]
----
%BASTION_PASSWORD%
----

. Log in to the *rhel8selinux1.{GUID}.internal* host:
+
[%nowrap]
----
[localhost ~]$ ssh rhel8selinux1.%GUID%.internal
----

. Log as root
+
[%nowrap]
----
[%USERNAME%@rhel8selinux1]$ sudo -i
[root@rhel8selinux1]
----

NOTE: Repeat steps #1-2 above on a second terminal (this terminal window will also be connected to *rhel8selinux1.%GUID%.internal*) via bookbag (click in top right corner for new terminal)

The first step is to install udica and container runtime engine, in this case the _podman_ engine will be used, and the rest of dependencies.

----
[root@rhel8selinux1]# dnf install -y udica podman setools-console container-selinux
----

Then, make sure that SELinux is in Enforcing mode.

----
[root@rhel8selinux1]# setenforce 1
[root@rhel8selinux1]# getenforce
Enforcing
----

=== Current situation

Let's use podman to start container with following parameters:

----
[root@rhel8selinux1]# podman run -v /home:/home:ro -v /var/spool:/var/spool:rw -p 21:21 -it ubi8 bash
----

 - Container will bind mount /home with read only perms
 - Container will bind mount /var/spool with read/write perms
 - Container will publish container's port 21 to the host

Access to the mounted */home* is not working:

----
[root@37a3635afb8f /]# cd /home/
[root@37a3635afb8f home]# ls
ls: cannot open directory '.': Permission denied
----

Also, access to the mounted */var/spool* is not working:

----
[root@37a3635afb8f home]# cd /var/spool/
[root@37a3635afb8f spool]# ls
ls: cannot open directory '.': Permission denied
[root@37a3635afb8f spool]# touch test
touch: cannot touch 'test': Permission denied
----

Because there is no allow rule for **container_t** to access */home* and access to */var/spool*.

The container runs with **container_t** type and **c447,c628** categories(categories are randomly generated so on your system numbers are different):

NOTE: Please run following commands in second opened terminal

----
[root@rhel8selinux1]# ps -efZ | grep container_t
system_u:system_r:container_t:s0:c447,c628 root 15361 15350  0 15:15 pts/0 00:00:00 bash
----

----
[root@rhel8selinux1]# sesearch -A -s container_t -t home_root_t -c dir -p read
[root@rhel8selinux1]#
[root@rhel8selinux1]# sesearch -A -s container_t -t var_spool_t -c dir -p read
[root@rhel8selinux1]#
----

On the other hand, what is completely allowed is network access.

----
[root@rhel8selinux1]# sesearch -A -s container_t -t port_type -c tcp_socket
allow container_net_domain port_type:tcp_socket { name_bind name_connect recv_msg send_msg };
allow sandbox_net_domain port_type:tcp_socket { name_bind name_connect recv_msg send_msg };

[root@rhel8selinux1]# sesearch -A -s container_t -t port_type -c udp_socket
allow container_net_domain port_type:udp_socket { name_bind recv_msg send_msg };
allow sandbox_net_domain port_type:udp_socket { name_bind recv_msg send_msg };
----

It would be great to restrict this access and allow the container to only bind on tcp port *21*.

=== Creating SELinux policy for container

To create a policy for the container, it's necessary to have running container for which a policy will be generated. The container from previous section will be used.

Let's find container's id using the *podman ps* command:

----
[root@rhel8selinux1]# podman ps
CONTAINER ID   IMAGE                             COMMAND   CREATED          STATUS              PORTS   NAMES
37a3635afb8f   registry.access.redhat.com/ubi8:latest   bash      15 minutes ago   Up 15 minutes ago           heuristic_lewin
----

The container ID is **37a3635afb8f**. (Your container ID will be different, please use yours.)

To create policy for it the **udica** tool can be used. The container will be inspected by running *podman inspect*. Udica takes one parameter which is name of created SELinux security policy.

----
[root@rhel8selinux1]# podman inspect 37a3635afb8f | udica my_container

Policy my_container with container id 37a3635afb8f created!

Please load these modules using:
[root@rhel8selinux1]# semodule -i my_container.cil /usr/share/udica/templates/{base_container.cil,net_container.cil,home_container.cil}

Restart the container with: "--security-opt label=type:my_container.process" parameter
----

Policy is generated. Let's follow the instructions from the output to install generated SELinux policy:

----
# semodule -i my_container.cil /usr/share/udica/templates/{base_container.cil,net_container.cil,home_container.cil}
----

Let's exit the running container and start new one.

----
[root@37a3635afb8f spool]# exit
[root@rhel8selinux1]# podman run --security-opt label=type:my_container.process -v /home:/home:ro -v /var/spool:/var/spool:rw -p 21:21 -it ubi8 bash
----

The container is now running with **my_container.process** type:

----
[root@rhel8selinux1]# ps -efZ | grep my_container.process
unconfined_u:system_r:container_runtime_t:s0-s0:c0.c1023 root 2275 434  1 13:49 pts/1 00:00:00 podman run --security-opt label=type:my_container.process -v /home:/home:ro -v /var/spool:/var/spool:rw -p 21:21 -it ubi8 bash
system_u:system_r:my_container.process:s0:c270,c963 root 2317 2305  0 13:49 pts/0 00:00:00 bash
----

Proof that SELinux is now allowing access to */home* and */var/spool* mount points:

----
[root@814ec56079e5 /]# cd /home
[root@814ec56079e5 home]# ls
ec2-user

[root@814ec56079e5 ~]# cd /var/spool/
[root@814ec56079e5 spool]# touch test
[root@814ec56079e5 spool]#
----
